dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=omni setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: Enh//EJy3I8lpC5uI4Vtua0dMgS478O5vLkXHWN+IfFGaFBGVFDcVzxQTjWxeqv6g5KAjucN2PB9vqN+9/oOQ3giNSf+7vPTo8Bk4GSUq924TK2gzJMOwEzQwx6M8MiLab+zyjgs9TQzzL9z1aCzTBI9bo3Ngbm2b9dh2fKMvo0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
