from typing import Literal

from .base import Base, BaseDelta

TaskStateT = Literal[1, 2, 3, 4, 5, 6, 7, 8, 9]

class TaskState:
    CREATED: Literal[1] = ...
    SCHEDULED: Literal[2] = ...
    RUNNING: Literal[3] = ...
    FINISHED: Literal[4] = ...
    CANCELED: Literal[5] = ...
    FAILED: Literal[6] = ...
    PAUSING: Literal[7] = ...
    PAUSED: Literal[8] = ...
    CANCELING: Literal[9] = ...

class Task(Base):
    task_state: TaskStateT

class TaskDelta(BaseDelta):
    task_state: TaskStateT
